LOGIN = "1"
GET_SERVERS = "2"
SERVER_LISTS = "3"
LOGIN_RESULT = "4"

UDP_LOGIN = "1"
UDP_UPDATE_POSITION = "2"
UDP_GET_OBJECT = "3"
UDP_SERVER_UPDATE = "4"
UDP_ATTACK = "5"
UDP_UPDATE_OBJECT = "6"

NOT_FOUND = "404"
